services:
  - type: web
    name: olx-emag-comparison
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000 