services:
  - type: web
    name: olx-emag-comparison
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.16
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1" 