services:
  - type: web
    name: olx-emag-comparison
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wget unzip
      wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/114.0.5735.90/linux64/chrome-linux64.zip"
      unzip chrome-linux64.zip
      mv chrome-linux64/chrome /usr/local/bin/google-chrome
      chmod +x /usr/local/bin/google-chrome
      rm -rf chrome-linux64.zip chrome-linux64
      wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/114.0.5735.90/linux64/chromedriver-linux64.zip"
      unzip chromedriver-linux64.zip
      mv chromedriver-linux64/chromedriver /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      rm -rf chromedriver-linux64.zip chromedriver-linux64
      pip install -r requirements.txt
      echo "Проверка на Chrome:"
      /usr/local/bin/google-chrome --version
      echo "Проверка на ChromeDriver:"
      /usr/local/bin/chromedriver --version
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1" 