services:
  - type: web
    name: olx-scraper
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget unzip xvfb libxi6 libgconf-2-4
      pip install -r requirements.txt
      python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
    startCommand: |
      export DISPLAY=:99
      Xvfb :99 -screen 0 1024x768x16 &
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DISPLAY
        value: ":99" 